name: Setup
description: Setup

inputs:
  sqls-version:
    description: "sqls version"
    required: false
    default: "latest"
  wasm-pack-version:
    description: "wasm-pack version"
    required: false
    default: "0.13.1"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v6
      with:
        go-version: "stable"

    - name: Install sqls
      run: go install github.com/sqls-server/sqls@${{ inputs.sqls-version }}
      shell: bash
      env:
        SQLS_VERSION: ${{ inputs.sqls-version }}

    - uses: chetan/git-restore-mtime-action@v2 # for Rust incremental build

    - name: Rust cache
      id: rust-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db
          sql-extraction/rs/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install wasm-pack if not installed
      shell: bash
      run: |
        if [ ! -x "$(command -v wasm-pack)" ] || [ "$(wasm-pack -V | cut -d' ' -f2)" != "$WASM_PACK_VERSION" ]; then
          cargo install --version $WASM_PACK_VERSION wasm-pack --force
        fi

      env:
        WASM_PACK_VERSION: ${{ inputs.wasm-pack-version }}

      # - name: Setup docker (missing on MacOS)
      #   if: runner.os == 'macos'
      #   run: |
      #     # Reference: https://github.com/actions/runner-images/issues/17#issuecomment-1537238473

      #     brew install docker
      #     colima start

      #     # For testcontainers to find the Colima socket
      #     # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
      #     sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      # - name: Start up DBs
      #   run: docker compose up -d

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: latest
        cache: "pnpm"
