[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
expect-test = "1.5.0"
pretty_assertions = "1.4.1"
proc-macro2 = { version = "1.0.92", features = ["span-locations"] }
quote = "1.0.37"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
syn = { version = "2.0.79", features = ["full", "visit", "extra-traits"] }
wasm-bindgen = { version = "0.2.97", features = ["serde-serialize"] }
