[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
expect-test = "1.5.0"
pretty_assertions = "1.4.0"
proc-macro2 = { version = "1.0.86", features = ["span-locations"] }
quote = "1.0.36"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
syn = { version = "2.0.68", features = ["full", "visit", "extra-traits"] }
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
